# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# inspired by examples here: https://github.com/snok/install-poetry

name: build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    # ----------------------------------------------
    #  test linux and mac; several python versions
    # ----------------------------------------------
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}

    steps:
      # ----------------------------------------------
      #       check out repo and set up python
      # ----------------------------------------------
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # ----------------------------------------------
      #         install and configure poetry
      # ----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # ----------------------------------------------
      #        load cached venv if cache exists
      # ----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      # ----------------------------------------------
      #  install dependencies if cache does not exist
      # ----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      # ----------------------------------------------
      #       install root project, if required
      # ----------------------------------------------
      - name: Install library
        run: poetry install --no-interaction

      # ----------------------------------------------
      #                 run linters
      # ----------------------------------------------
      #- name: Run linters
      #  run: |
      #    poetry run flake8 .
      #    poetry run black . --check
      #    poetry run isort .

      # ----------------------------------------------
      #                 run tests
      # ----------------------------------------------
      - name: Test with pytest
        run: |
          poetry run pytest --cov=./pzflow --cov-report=xml -n 10

      # ----------------------------------------------
      #          upload coverage to Codecov
      # ----------------------------------------------
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
